from .exceptions import MalformedArgument as MalformedArgument, MissingArgument as MissingArgument, UnsupportedArgument as UnsupportedArgument
from collections.abc import Callable as Callable

def is_value(d: dict, key: str, data_type: type) -> bool: ...
def list_of(sequence: list, data_type: type) -> bool: ...
def matching(dictionary: dict, pattern: dict) -> None: ...
